### ISSUE TITLE
feat: readme

### ISSUE THREAD

**Issue by AceLikesGhosts** [iSlammedMyKindle/kindle-twitch-oauth#3]
add documentation in a readme or the `index.ts` please and thank u love you

**Comment by iSlammedMyKindle** [comment]
Definitely worth it; it would let more people figure out how this thing works so they can use it in other projects

I've been doing a new mentality lately called "MVP" (minimum viable product) - so a lot of neglect is happening in terms of stuff that's not required to make my things to work.

It's likely I will get back to this when I'm done working on the major things I've been building. There is at least one more project that I will be assembling before going back to document my steps and other small chores

**Comment by AceLikesGhosts** [comment]
😐

**Comment by iSlammedMyKindle** [comment]
Putting this here to remind myself to do this, I have one major project left so after that I'll come back here and do nitpicking
